AWSTemplateFormatVersion: "2010-09-09"
Description: >-  
  >- Develop a CloudFormation template called "networking" that includes the following AWS networking components:
  >- - VPC (with "EnableDnsSupport" and "EnableDnsHostnames" options enabled);
  >- - non-default route table;
  >- - two subnets in different availability zones associated with the route table (with "MapPublicIpOnLaunch" option enabled);
  >- - Internet gateway attached to the VPC;
  >- - default route in the route table pointing to the Internet gateway.
  >-
  >- The template must have the following input parameters:
  >-  - CIDR block for VPC (a default value must be pre-defined);
  >-  - CIDR block for subnet A (a default value must be pre-defined);
  >-  - CIDR block for subnet B (a default value must be pre-defined).
  >-  - The template must have the following outputs:
  >-  - VPC ID;
  >-  - subnet A ID;
  >-  - subnet B ID.

Parameters:
  MyCidrVpc:
    Description: CIDR block for VPC 
    Type: String
    Default: 10.10.0.0/16
  MyCidrA:
    Description: CIDR block for subnet A 
    Type: String
    Default: 10.10.1.0/24  

  MyCidrB:
    Description: CIDR block for subnet B 
    Type: String
    Default: 10.10.2.0/24




Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MyCidrVpc
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: mp2019

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVpc

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVpc
      InternetGatewayId: !Ref MyInternetGateway
  
  MyDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway
  
  MySubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref MyVpc
      MapPublicIpOnLaunch: true
      CidrBlock: !Ref MyCidrA
  
  MySubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref MyVpc
      CidrBlock: !Ref MyCidrB
      MapPublicIpOnLaunch: true     

Outputs:
  MyVpcIdOutput:
    Description: MyVpc ID
    Value: !Ref MyVpc
  MySubnetAIdOutput:
    Description: My Subnet A ID
    Value: !Ref MySubnetA
  MySubnetBIdOutput:
    Description: My Subnet B ID
    Value: !Ref MySubnetB