AWSTemplateFormatVersion: "2010-09-09"
Description: >-  
  >- Develop a CloudFormation template called "networking" that includes the following AWS networking components:
  >- - VPC (with "EnableDnsSupport" and "EnableDnsHostnames" options enabled);
  >- - non-default route table;
  >- - two subnets in different availability zones associated with the route table (with "MapPublicIpOnLaunch" option enabled);
  >- - Internet gateway attached to the VPC;
  >- - default route in the route table pointing to the Internet gateway.
  >-
  >- The template must have the following input parameters:
  >-  - CIDR block for VPC (a default value must be pre-defined);
  >-  - CIDR block for subnet A (a default value must be pre-defined);
  >-  - CIDR block for subnet B (a default value must be pre-defined).
  >-  - The template must have the following outputs:
  >-  - VPC ID;
  >-  - subnet A ID;
  >-  - subnet B ID.

Parameters:
  MyCidrVpc:
    Description: CIDR block for VPC 
    Type: String
    Default: 10.10.0.0/16

Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MyCidrVpc
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: mp2019

Outputs:
  OutputName:
    Description: MyVpc ID
    Value: !Ref MyVpc