AWSTemplateFormatVersion: "2010-09-09"
Description: >-  
  >- >-Develop a CloudFormation template called "database" that includes the following RDS database and related components:
  >- - DB subnet group that includes subnets created in a previous task;
  >- - DB parameter group of "MySQL5.7" family with "slow_query_log" set according to template parameter value;
  >- - RDS instance using the created subnet / parameter groups, with 8 GB of General Purpose SSD storage, and having "Admin" and "RDS" security groups attached. "Multi-AZ" option should NOT be enabled.
  >-
  >- The template must have the following input parameters:
  >- - IDs of subnets to place RDS instance in;
  >- - IDs of "Admin" and "RDS" security groups;
  >- - RDS instance class (a list of allowed values must be pre-defined, "db.t2.micro" being the default);
  >- - MySQL "slow_query_log" setting (allowed values: 0 or 1);
  >- - database username;
  >- - database password (this value must not be visible when entered during stack creation).
  >-
  >- The template must have the following outputs:
  >- - RDS endpoint address.
  >- 
  


Parameters:
  MyRdsSubnetIds: 
    Description: "IDs of subnets to place RDS instance in" 
    Type: List<AWS::EC2::Subnet::Id>

  MyRdsSgIds:
    Description:  "IDs of security groups"
    Type: List<AWS::EC2::SecurityGroup::Id>

  MyRdsInstanceClass:
    Description: "RDS instance class"
    Type: String
    Default: db.t2.micro
    AllowedValues: 
      - db.t2.micro
      - db.t2.medium
      - db.t2.small
      - db.t2.large    

  MyRdsSqlSetting:
    Description: "MySQL slow_query_log parameter"
    Type: Number
    Default: 1
    AllowedValues:
      - 1
      - 0
    
  MyRdsDatabaseUser:
    Description: "Database username"
    Type: String
  
  MyRdsDatabasePassword:
    Description: "Database password"
    Type: String
    NoEcho: true


Resources:
  MyRdsDbParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "DB parameter group of MySQL family with slow_query_log"
      Family: "MySQL5.7" 
      Parameters:
        slow_query_log: !Ref MyRdsSqlSetting
  
  
  MyRdsDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Existing public subnets"
      SubnetIds: !Ref MyRdsSubnetIds
  
  
  MyRdsDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "8"
      DBInstanceClass: !Ref MyRdsInstanceClass
      DBName: "MyCftDb"
      DBParameterGroupName: !Ref MyRdsDbParameterGroup
      DBSubnetGroupName: !Ref MyRdsDbSubnetGroup
      Engine: mysql
      EngineVersion: "MySQL 5.7" 
      MasterUsername: !Ref MyRdsDatabaseUser
      MasterUserPassword: !Ref MyRdsDatabasePassword
      MultiAZ: false
      PubliclyAccessible: true
      VPCSecurityGroups: !Ref MyRdsSgIds

Outputs:
  MyRdsSgOutput:
    Description: "RDS endpoint address"
    Value: !GetAtt MyRdsDbInstance.Endpoint.Address
